### ISSUE TITLE
Lua error with latest version

### ISSUE THREAD

**Issue by elvador** [Lleafll/doom-shards#5]
https://gist.github.com/elvador/69aea6039ac7b9dd41d6c046f6d8f836

**Comment by rluna68** [comment]
same here - started yesterday
Message: Interface\AddOns\DoomShards\Core\Specs.lua:131: attempt to perform arithmetic on field 'pandemic' (a nil value)
Time: 02/02/17 18:56:30
Count: 1
Stack: (tail call): ?
Interface\AddOns\DoomShards\Core\Specs.lua:131: in function `CalculateExpiration'
Interface\AddOns\DoomShards\Core\SpecsConfig.lua:174: in function `Refresh'
Interface\AddOns\DoomShards\Core\Core.lua:91: in function `Refresh'
Interface\AddOns\DoomShards\Core\Core.lua:145: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[15]"]:4: in function <[string "safecall Dispatcher[15]"]:4>
[C]: ?
[string "safecall Dispatcher[15]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Zerric** [comment]
Same error as the original poster, some additional information: I'm not getting the error in demonology spec, but while in affliction spec it seems to trigger when refreshing agony while in pandemic range.

**Comment by Lleafll** [comment]
Thank you all for your detailed bug reports.
I've fixed the issue and will push a release version as soon as possible.

**Comment by rluna68** [comment]
Thank you very much for your efforts.
