### ISSUE TITLE
Lagging when Refreshing Agony

### ISSUE THREAD

**Issue by GhostFacedNinja** [Lleafll/doom-shards#6]
Since wednesday 1st feb 17, I am getting a lag spike when refreshing agony on a target.

It only occurs on refresh, never on first application. And then causes a ~0.1-1s lag spikes on refresh. This seems to depend on how high the agony stacks are, in that refreshing on low stacks is quite often fine, but refreshing high stacks always causes a spike.

I run quite a few addons so I disabled everything and tested each in isolation. Doom Shards was the culprit.

**Comment by Lleafll** [comment]
There was an issue which caused a Lua error after refreshing Agony which is now fixed in v25.
Please check if the issue persists with this version.

**Comment by GhostFacedNinja** [comment]
I updated to v25 and this issue is now fixed.

That was quick! Nice one :)
